### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by mihaimunteanu28** [ruoccofabrizio/azure-open-ai-embeddings-qna#26]
Hello Ruocco,

I managed to add a document, but when I start asking questions I keep getting this error:

```
ValueError: not enough values to unpack (expected 3, got 2)
Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/usr/local/src/myscripts/OpenAI_Queries.py", line 74, in <module>
    st.session_state['full_prompt'], st.session_state['response'], st.session_state['source_file'] = utils.get_semantic_answer(df, question, st.session_state['prompt'] ,model=model, engine='davinci', tokens_response=st.tokens_response, temperature=st.temperature
```

Could you please help me with this? Thanks a lot!

**Comment by mifurm** [comment]
### it seems this problem is related to not rebuild docker images on docker hub; once I have rebuild them and did some changes in the repo to reference to my images, it works well, have a look into this commit: https://github.com/kubasiak/azure-open-ai-embeddings-qna/compare/main...mifurm:azure-open-ai-embeddings-qna:main

**Comment by ruoccofabrizio** [comment]
Thanks for the heads up, docker image fixed.
